version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - database
    networks:
      - internal
    volumes:
      - ./:/var/www/html/
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - internal

volumes:
  database_data:

networks:
  internal:
